### ISSUE TITLE
Void parameter sets should not require declaration

### ISSUE THREAD

**Issue by jwhpryor** [google/jni-bind#2]
Empty returns, constructors, and methods should not require specification.

**Comment by Harshitjoshi133** [comment]
Can I work on it

**Comment by jwhpryor** [comment]
Sure!  I would start by looking at class.h and method.h.  Also, I don't know what your setup is like, and I wouldn't be surprised if you need to resolve some blockages (i.e. https://github.com/google/jni-bind/issues/42).

This is obviously gating for 1.0 release, but I may not be able to do much in the immediate term.  If you can unblock that, it would be a help.

**Comment by Harshitjoshi133** [comment]
I thought it would be easy but now I am getting what to do

**Comment by jwhpryor** [comment]
Basically, [`::jni::Method` ](https://github.com/google/jni-bind/blob/main/implementation/method.h) take [`::jni::Params`](https://github.com/google/jni-bind/blob/main/implementation/params.h) which is tedious if there are no params.

i.e. I must write this:

```cpp
Method {"Foo", Return{}, Params{}}
```

when I want to write this:
```cpp
Method {"Foo", Return{}}
```

The task is to write a constructor for `Method` (and probably a CTAD guide) so this is possible.

**Comment by jwhpryor** [comment]
I seem to be seeing issues when these classes are being used as return values in chained calls.  I'm going to investigate.

**Comment by jwhpryor** [comment]
I haven't seen this failure in a long time and I don't know if I imagined it or not. I'm going to close this for now and can reopen if it continues to be an issue.
