### ISSUE TITLE
Add "NewReference" for Global and Local 

### ISSUE THREAD

**Issue by jwhpryor** [google/jni-bind#41]
It's legitimate to want to copy a local or global and this should be supported.

e.g.  a syntax like:
`LocalObject<kClass>  obj { obj, ShallowCopy{} };`

**Comment by jwhpryor** [comment]
This would be very similar to `GlobalObject` creation as a source for copying implementation from.

**Comment by Harshitjoshi133** [comment]
can i work on this

**Comment by jwhpryor** [comment]
Doh, I actually may have taken care of the bulk of this literally earlier today (search for `CreateCopy`) 🤦🏻‍♂️. 

https://github.com/google/jni-bind/commit/4d059ed27815abdde9d0b4be583b83c63295be63

That said, there's actually no meaningful E2E test. That would be both helpful, and probably a good intro to project.

Alternatively, https://github.com/google/jni-bind/issues/2 is unlikely to be finished soon, and is likely also a good spot to start.
